
version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: fill_data_webapp
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    volumes:
      - ./fill_data_webapp:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload

volumes:
  postgres_data:
