
version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
