global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "postgres-performance-insights-exporter"
    scrape_interval: 1s
    static_configs:
      - targets: ['pg-exporter:9153']
